// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onMessengerChange();

String messenger;
float sensor_temperature;
bool heater_one;
bool heater_two;

void initProperties(){

  ArduinoCloud.addProperty(messenger, READWRITE, ON_CHANGE, onMessengerChange);
  ArduinoCloud.addProperty(sensor_temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(heater_one, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(heater_two, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
